export const GET_CONTACTS = 'GET_CONTACTS';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const GET_CONTACT = 'GET_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const SORT_CONTACTS_ASC = 'SORT_CONTACTS_ASC';
export const SORT_CONTACTS_DESC = 'SORT_CONTACTS_DESC';
